### ISSUE TITLE
Auto completion but no syntax highlighting

### ISSUE THREAD

**Issue by choogiesaur** [raohmaru/psoasm-npp-udl#1]
Hi nice work on this!!
I've placed the PSO_asm.xml file in plugins/APIs and now I get opcode autocompletion
However under Language, I don't see PSO Asm, any idea why?

**Comment by raohmaru** [comment]
Hi @choogiesaur!
Thanks for your feedback :)

To add the new language to Notepad++, please follow these steps:

1. Download UDL file [PSO_asm.xml](https://raw.githubusercontent.com/raohmaru/psoasm-npp-udl/master/udl/PSO_asm.xml).
2. Open Notepad++.
3. Go to "Language > Define your language...".
4. Click on "Import..." button, browse to the location where `PSO_asm.xml` was saved and open it.
5. Restart Notepad++.
